#+TITLE: MacOS Automator app for Emacs Daemon+Client
* MacOS Daemon+Client App
   The =ec.command= file is meant to be the shell script of a mac automator app.
The app ends up being 19 mb so I'm not checking it in with git and instead, I
track =ec.command= and give instructions to make an app from it.

- Opening files with the app will open them in the currently running emacs daemon using emacsclient.  The script contains logic to create a new frame if necessary.
- The app can start the daemon if it is not running.  In that case the user is prompted and can choose "cancel" to start it themselves their way or "ok" to let the script start the daemon.

These steps can be followed to create the app from this script, change its icon
and define a file association for orgmode files.

** Create App
Launch Automator, do
- File \rightarrow New : Application (self running workflow) : Choose
- Top left : Search bar : "Run Shell Script" : Double Click
- Paste =ec.command= into the text area.
- Top Right : Select "As Arguments" for "Pass input" (for MacOS to open files with this app)
- File \rightarrow Export : Save in /Applications or ~/Applications
- If environment not configured in ~/.zshenv see TODO in the file

** Change App icon
In finder, locate the Emacs app and the new Automator app.
- Right click the app : Get info
- Right click the Emacs App : Get info
- Click on the emacs icon in the Emacs App Info window, do CMD-C
- Click on the icon in the exported app Info window, do CMD-V

** File association
Locate an orgmode file in Finder
- Right click an orgmode file: Get Info
- In section "Open With" : Select other, find exported app and select it
- Click on change all to associate new app with all orgmode files
